# MySQL configs
mysql:
  user: root
  password: 12345678
  address: localhost:3306
  database: db_goim
# Server machine ID
machineId: 6001
# etcd configs
etcd:
  endpoints:
    - localhost:2379
naming: etcd
# redis configs
redis:
  address: localhost:6379
# message queue configs
messageQueue: nsq
nsq:
  lookupAddresses:
    - localhost:4161
  nsqdAddress: localhost:4150
# deploy environment
environment: development
metrics:
  promHttpAddr: localhost:50007
trace:
  jaeger:
    collectorEndpoint: http://localhost:14268/api/traces