# MySQL configs
mysql:
  user: root
  password: 12345678
  address: localhost:3306
  database: db_goim
# Server machine ID
machineId: 4001
# RPC Server configs
rpcServer:
  Address: localhost:9200
# redis configs
redis:
  address: localhost:6379
# etcd configs
etcd:
  endpoints:
    - localhost:2379
naming: etcd

environment: development
metrics:
  promHttpAddr: localhost:50004
trace:
  jaeger:
    collectorEndpoint: http://localhost:14268/api/traces