mysql:
  user: root
  password: 991228
  address: 127.0.0.1:3306
consul:
  address: 127.0.0.1:8500
machineId: 201
kafka:
  addrs:
    - 127.0.0.1:9092
rpcServer:
  address: 127.0.0.1:9100
tokenSecretKey: xdedfaedcdafefadfaeadfdc